baseURL = 'https://rizqystore.pages.dev/'
languageCode = 'id'
title = 'Rizqy Store'
theme = 'store'
enableRobotsTXT = 'true'
paginate = 10
summaryLength = 10

[params]
  Description = 'Rizqy Store adalah Toko Online yang hanya menjual produk khusus untuk ibu-ibu dan nenek-nenek, seperti alat prabot rumah tangga, skin care, fashion, dan lain-lainnya.'
  favicon = 'https://img.icons8.com/512/202124/online-store.png'
  twitter = 'Rizqy Store'

[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 5
    ordered = false
[markup.goldmark.renderer]
  unsafe = true
[related]
  includeNewer = true
  threshold = 80
  toLower = false

  [[related.indices]]
    name = "tags"
    weight = 100
  [[related.indices]]
    name = "keywords"
    weight = 80
  [[related.indices]]
    name = "title"
    weight = 70